-- Delete tables
DROP TABLE IF EXISTS build;
DROP TABLE IF EXISTS build_target;
DROP TABLE IF EXISTS build_source;
DROP TABLE IF EXISTS snapshot;
DROP TABLE IF EXISTS project;
DROP TABLE IF EXISTS project_users;

-- Delete types
DROP TYPE IF EXISTS BUILD_STATUS;
DROP TYPE IF EXISTS SNAPSHOT_STATUS;
DROP TYPE IF EXISTS PROJECT_SOURCE;


-- Delete functions
DROP FUNCTION IF EXISTS trigger_set_timestamp;

-- Delete extensions
DROP EXTENSION IF EXISTS "uuid-ossp";