version: "3.7"
services:
  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - "4436:4436"
      - "4437:4437"
    networks:
      - intranet
  minio:
    image: docker.io/bitnami/minio:2024
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/bitnami/minio/data
    networks:
      - intranet
    environment:
      - MINIO_ROOT_USER=pixeleye
      - MINIO_ROOT_PASSWORD=CHANGEME
      - MINIO_DEFAULT_BUCKETS=pixeleye
  postgres:
    build:
      context: ./config
      dockerfile: ./Dockerfile.psql
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data

    environment:
      - POSTGRES_USER=guest
      - POSTGRES_PASSWORD=CHANGEME
      - POSTGRES_DB=guest
      - PGPORT=5431
      - POSTGRES_MULTIPLE_DATABASES=pixeleye,kratos
    ports:
      - "5431:5431"
    networks:
      - intranet
  rabbitmq:
    image: rabbitmq:3.13
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=CHANGEME
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - intranet
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
  pixeleye-migrate:
    image: pixeleye/pixeleye-migrations:latest
    environment:
      - DB_HOST=postgres
      - DB_PORT=5431
      - DB_NAME=pixeleye
      - DB_USERNAME=guest
      - DB_PASSWORD=CHANGEME
      - DB_PARAMS=sslmode=disable
    restart: on-failure
    networks:
      - intranet

  kratos-migrate:
    image: oryd/kratos:v1.0.0
    environment:
      - DSN=postgres://guest:CHANGEME@postgres:5431/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - type: bind
        source: ./config
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    networks:
      - intranet
  kratos:
    depends_on:
      - kratos-migrate
    image: "oryd/kratos:v1.0.0"
    ports:
      - "4433:4433" # public
      - "4434:4434" # admin
    restart: unless-stopped
    environment:
      - DSN=postgres://guest:CHANGEME@postgres:5431/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
      - LOG_LEVEL=trace
    command: serve -c /etc/config/kratos/kratos.yml --watch-courier
    volumes:
      - type: bind
        source: ./config
        target: /etc/config/kratos
    networks:
      - intranet
networks:
  intranet:
    driver: bridge

volumes:
  postgres-data:
  rabbitmq-data:
  minio-data:
