version: "3.7"
services:
  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - "4436:4436"
      - "4437:4437"
    networks:
      - intranet
  minio:
    image: docker.io/bitnami/minio:2022
    ports:
      - '9000:9000'
    networks:
      - intranet
    volumes:
      - 'minio-data:/data'
    environment:
      - MINIO_ROOT_USER=pixeleye
      - MINIO_ROOT_PASSWORD=CHANGEME
      - MINIO_DEFAULT_BUCKETS=pixeleye
  postgres:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - type: bind
        source: ./config/init-user-db.sh
        target: /docker-entrypoint-initdb.d/init-user-db.sh

    environment:
      - POSTGRES_USER=guest
      - POSTGRES_PASSWORD=CHANGEME
      - POSTGRES_DB=guest
      - PGPORT=5431
      - POSTGRES_MULTIPLE_DATABASES=pixeleye,kratos
    ports:
      - "5431:5431"
    networks:
      - intranet
  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=CHANGEME
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - intranet
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
  pixeleye-migrate:
    image: pixeleye/pixeleye-migrations:latest
    environment:
      - DB_HOST=postgres
      - DB_PORT=5431
      - DB_NAME=pixeleye
      - DB_USERNAME=guest
      - DB_PASSWORD=CHANGEME
      - DB_PARAMS=sslmode=disable
    restart: on-failure
    networks:
      - intranet
  pixeleye-backend:
    ports:
      - "5000:5000"
    depends_on:
      - pixeleye-migrate
    image: pixeleye/pixeleye:latest
    restart: unless-stopped
    environment:
      - STAGE_STATUS=prod
      - BACKEND_URL=http://localhost:5000
      - FRONTEND_URL=http://localhost:3000
      - DB_HOST=postgres
      - DB_PORT=5431
      - DB_NAME=pixeleye
      - DB_USERNAME=guest
      - DB_PASSWORD=CHANGEME
      - DB_SSL_MODE=disable
      - DB_MAX_CONNECTIONS=20
      - DB_MAX_IDLE_CONNECTIONS=4
      - DB_MAX_LIFTTIME_CONNECTIONS=1
      - S3_BUCKET=pixeleye
      - S3_ENDPOINT=http://minio:9000
      - S3_ACCESS_KEY_ID=pixeleye
      - S3_KEY_SECRET=CHANGEME
      - ORY_URL=http://kratos:4433
      - ORY_ADMIN_URL=http://kratos:4434
      - ORY_API_KEY=
      - AMQP_USER=guest
      - AMQP_PASSWORD=CHANGEME
      - AMQP_HOST=rabbitmq
      - AMQP_PORT=5672
      - AMQP_VHOST=/
      - AMQP_TLS=false
      - SMTP_HOST=mailslurper
      - SMTP_PORT=1025
      - SMTP_USER=test
      - SMTP_PASSWORD=test
      - SMTP_SENDER=no-reply@pixeleye.sh
      # - GITHUB_APP_NAME= # optional if you want to use the github login
      # - GITHUB_APP_CLIENT_ID= # optional if you want to use the github login
      # - GITHUB_APP_ID= # optional if you want to use the github login
      # - GITHUB_APP_CLIENT_SECRET= # optional if you want to use the github login
      # - GITHUB_APP_PRIVATE_KEY= # optional if you want to use the github login
    networks:
      - intranet
  pixeleye-frontend:
    image: pixeleye/pixeleye-frontend:latest
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_ORY_URL=http://kratos:4433
      - ORY_URL=http://kratos:4433
      - NEXT_PUBLIC_ORY_URL=http://localhost:4433
      - BACKEND_URL=http://pixeleye-backend:5000
      # - GITHUB_APP_NAME= # optional if you want to use the github login
    networks:
      - intranet
    ports:
      - "3000:3000"

  kratos-migrate:
    image: oryd/kratos:v1.0.0
    environment:
      - DSN=postgres://guest:CHANGEME@postgres:5431/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - type: bind
        source: ./config
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    networks:
      - intranet
  kratos:
    depends_on:
      - kratos-migrate
    image: "oryd/kratos:v1.0.0"
    ports:
      - "4433:4433" # public
      - "4434:4434" # admin
    restart: unless-stopped
    environment:
      - DSN=postgres://guest:CHANGEME@postgres:5431/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
      - LOG_LEVEL=trace
    command: serve -c /etc/config/kratos/kratos.yml --watch-courier
    volumes:
      - type: bind
        source: ./config
        target: /etc/config/kratos
    networks:
      - intranet
networks:
  intranet:

volumes:
  postgres-data:
  rabbitmq-data:
  minio-data:
