export default function Head() {
  return (
    <>
      <title>Pixeleye</title>
      <meta name="description" content="Generated by create-t3-app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
