name: Pixeleye CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  paths-filter:
    name: Paths filter
    runs-on: ubuntu-latest
    outputs:
      migrations: ${{ steps.filter.outputs.migrations }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            migrations:
              - 'apps/backend/platform/migrations'
  node-ci:
    name: Node - Build, Lint, Test, Types
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm turbo lint

      - name: Test
        run: pnpm turbo test

      - name: Types
        run: pnpm turbo types

      - name: Build
        run: pnpm turbo build

  golang-ci:
    name: Golang - Lint, Test, Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53
          args: --timeout=5m
          working-directory: ./apps/backend

      - name: Install dependencies
        run: |
          cd apps/backend  
          go mod download
          go mod verify

      - name: Build
        run: |
          cd apps/backend
          go build -v ./...

      - name: Test
        run: |
          cd apps/backend
          go test -v ./...

  atlas-ci:
    name: Atlas - Linting
    runs-on: ubuntu-latest
    needs: paths-filter
    if: github.ref == 'refs/heads/main' || needs.paths-filter.outputs.migrations == 'true'
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: pass
          POSTGRES_DB: test
        ports:
          - 5430:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v3.0.1
        with:
          fetch-depth: 0
      - uses: ariga/atlas-action@v0
        with:
          dir: apps/backend/platform/migrations
          dir-format: atlas
          dev-url: postgres://postgres:pass@localhost:5430/test?sslmode=disable

  api-tests:
    name: API Tests
    runs-on: ubuntu-latest
    needs: [golang-ci, node-ci]

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: pass
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      rabbitmq:
        image: rabbitmq:3-alpine
        env:
          RABBITMQ_DEFAULT_USER: rabbitmq
          RABBITMQ_DEFAULT_PASS: rabbitmq
        ports:
          - 5672:5672
          - 15672:15672
        options: --health-cmd "rabbitmq-diagnostics -q check_running" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Install Atlas
        run: |
          curl -sSf https://atlasgo.sh | sh
      - run: |
          atlas migrate apply --dir file://apps/backend/platform/migrations/ -u 'postgres://postgres:pass@localhost:5432/test?sslmode=disable'

      - name: Setup golang
        uses: actions/setup-go@v4
        with:
          go-version: "^1.20"

      - name: Install go dependencies
        working-directory: ./apps/backend
        run: |
          go mod download
          go mod verify

      - name: start go server
        working-directory: ./apps/backend
        run: go run main.go &

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"


      - name: Create .env file
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_ORY_ENDPOINT: ${{ secrets.SECRET_KEY }}
          envkey_ORY_API_KEY: ${{ secrets.SECRET_KEY }}
          envkey_SERVER_ENDPOINT: localhost:5000


      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies node
        run: pnpm install

      - name: Run api tests
        run: pnpm turbo test:api
