# name: Node CI

# on:
#   push:
#     branches: ["main"]
#   pull_request:
#     types: [opened, synchronize]

# jobs:
#   node-ci:
#     name: Node - Build, Lint, Test, Types
#     timeout-minutes: 15
#     runs-on: ubuntu-latest
#     env:
#       TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
#       TURBO_TEAM: ${{ vars.TURBO_TEAM }}

#     steps:
#       - name: Check out code
#         uses: actions/checkout@v3
#         with:
#           fetch-depth: 2

#       - name: Setup Node.js environment
#         uses: actions/setup-node@v3
#         with:
#           node-version: 18
#           cache: "pnpm"

#       - name: Install pnpm
#         uses: pnpm/action-setup@v2
#         with:
#           version: 8
#           run_install: false

#       - name: Get pnpm store directory
#         shell: bash
#         run: |
#           echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

#       - uses: actions/cache@v3
#         name: Setup pnpm cache
#         with:
#           path: ${{ env.STORE_PATH }}
#           key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
#           restore-keys: |
#             ${{ runner.os }}-pnpm-store-

#       - name: Install dependencies node
#         run: pnpm install

#       - uses: pnpm/action-setup@v2.0.1
#         with:
#           version: 6.32.2

#       - name: Lint
#         run: pnpm turbo lint

#       - name: Test
#         run: pnpm turbo test

#       - name: Types
#         run: pnpm turbo types

#       - name: Build
#         run: pnpm turbo build
